"use client";
import { useState } from "react";
const cats=["AI & Technology","Business","History & Mysteries","Tamil Nadu & India","Finance","Education","Viral Facts"];
const samples=[
{cat:"AI & Technology",title:"7 AI tools that can save a small business hours every week",score:94},
{cat:"History & Mysteries",title:"The expedition that vanished without a clear explanation",score:91},
{cat:"Education",title:"Why airplanes can fly despite weighing hundreds of tonnes",score:88},
{cat:"Tamil Nadu & India",title:"10 remarkable places in Tamil Nadu most tourists miss",score:86},
{cat:"Business",title:"How a tiny company turned one simple idea into a global business",score:84},
{cat:"Finance",title:"Why the value of money changes over time",score:82},
{cat:"Viral Facts",title:"10 surprising facts that sound fake but are true",score:80}];
export default function Home(){const[cat,setCat]=useState(cats[0]);const[ideas,setIdeas]=useState<any[]>([]);const[approved,setApproved]=useState<string[]>([]);const[loading,setLoading]=useState(false);const[status,setStatus]=useState("");
async function generate(){setLoading(true);setStatus("Generating ideas…");try{const r=await fetch("/api/ideas",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({category:cat})});const d=await r.json();setIdeas(Array.isArray(d.ideas)?d.ideas:[]);}catch{setIdeas(samples.filter(x=>x.cat===cat))}finally{setLoading(false);setStatus("")}}
return <main><header><div><div className="eyebrow">AI MEDIA OPERATING SYSTEM</div><h1>Content Agent</h1><p>Discover → Research → Create → Approve → Publish → Learn</p></div><div className="pill">● MVP ONLINE</div></header><section className="stats"><div><b>7</b><span>Categories</span></div><div><b>{ideas.length||1}</b><span>Ideas</span></div><div><b>{approved.length}</b><span>Approved</span></div><div><b>0</b><span>Published</span></div></section><section className="panel"><div className="toolbar"><div><h2>Topic Engine</h2><p>Choose a niche and generate high-potential topics. Politics excluded.</p></div><div className="controls"><select value={cat} onChange={e=>setCat(e.target.value)}>{cats.map(c=><option key={c}>{c}</option>)}</select><button onClick={generate} disabled={loading}>{loading?"Generating…":"Generate ideas"}</button></div></div>{status&&<div className="pill status">{status}</div>}<div className="grid">{(ideas.length?ideas:samples.filter(x=>x.cat===cat)).map((x:any,i)=><article className="card" key={i}><div className="cardtop"><span>{x.category||x.cat}</span><strong>{x.score}/100</strong></div><h3>{x.title}</h3><p>{x.description||"Curiosity-led topic designed for an original, useful video."}</p><div className="actions"><button className="ghost" onClick={()=>alert("Research pipeline is the next stage of the MVP.")}>Research</button><button className={approved.includes(x.title)?"approved":"approve"} onClick={()=>setApproved(a=>a.includes(x.title)?a.filter(t=>t!==x.title):[...a,x.title])}>{approved.includes(x.title)?"✓ Approved":"Approve"}</button></div></article>)}</div></section><section className="pipeline"><h2>Production pipeline</h2><div className="steps">{["Topic","Research","Script","Video","QA","Your approval","YouTube","Analytics"].map((s,i)=><div key={s} className={i===5?"active":""}><em>{i+1}</em>{s}{i<7&&<span>→</span>}</div>)}</div></section><footer>Human approval is required before publishing. Add AI and YouTube credentials for live generation and publishing.</footer></main>}